// <auto-generated />
using System;
using AMS.Domains.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260313094257_RemoveDaysOfWeek")]
    partial class RemoveDaysOfWeek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMS.Domains.Entities.AssignedStudent", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Oid");

                    b.HasIndex("ClassScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("AssignedStudents");
                });

            modelBuilder.Entity("AMS.Domains.Entities.Class", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Oid"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Oid");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("AMS.Domains.Entities.ClassSchedule", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndScheduleTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartScheduleTime")
                        .HasColumnType("interval");

                    b.HasKey("Oid");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassSchedules");
                });

            modelBuilder.Entity("AMS.Domains.Entities.DailyAttendance", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Oid");

                    b.HasIndex("StudentId");

                    b.ToTable("DailyAttendances");
                });

            modelBuilder.Entity("AMS.Domains.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("HolidayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("VacationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Oid");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("AMS.Domains.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Oid");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("AMS.Domains.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Oid");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("AMS.Domains.Entities.AssignedStudent", b =>
                {
                    b.HasOne("AMS.Domains.Entities.ClassSchedule", "ClassSchedule")
                        .WithMany("AssignedStudents")
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS.Domains.Entities.StudentProfile", "StudentProfile")
                        .WithMany("AssignedStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchedule");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("AMS.Domains.Entities.ClassSchedule", b =>
                {
                    b.HasOne("AMS.Domains.Entities.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("AMS.Domains.Entities.DailyAttendance", b =>
                {
                    b.HasOne("AMS.Domains.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("AMS.Domains.Entities.Class", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("AMS.Domains.Entities.ClassSchedule", b =>
                {
                    b.Navigation("AssignedStudents");
                });

            modelBuilder.Entity("AMS.Domains.Entities.StudentProfile", b =>
                {
                    b.Navigation("AssignedStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
